name: Build 3DS CIA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Standalone Bannertool
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -L -O bannertool.zip https://github.com
          unzip bannertool.zip -d bannertool_dir
          sudo cp bannertool_dir/linux-x64/bannertool /opt/devkitpro/tools/bin/bannertool
          sudo chmod +x /opt/devkitpro/tools/bin/bannertool

      - name: Fix deprecated code
        run: |
          git config --global --add safe.directory /__w/Ghost-eShop-Homebrew/Ghost-eShop-Homebrew
          sed -i 's/AM_DeleteAppTitle/AM_DeleteTitle/g' source/utils/cia.cpp
          sed -i '1s/^/#include <sstream>\n/' source/utils/download.cpp

      - name: Run Build
        run: |
          make clean || true
          make

      - name: Upload CIA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-3ds-cia
          path: |
            *.cia
            build/*.cia
            bin/*.cia
          if-no-files-found: warn
